### ISSUE TITLE
原文的权重太大，大佬的模型是用哪个backbone呢

### ISSUE THREAD

**Issue by liufqing** [MR-520DAI/UFAST_NCNN#1]
原文的权重太大，大佬的模型是用哪个backbone呢

**Comment by MR-520DAI** [comment]
你好，我用的resnet18，但是把卷积核的维度给砍半，输出层的全连接也砍了很多，具体忘记了，因此我提供的模型文件会小很多。
PS：UFAST这个算法是处理不了变道的情况的，慎用！

**Comment by liufqing** [comment]
大佬，UFAST 是不改变车道的情况的意思是不改变车道数量不，比如4车道行驶，不能用于2车道。是这个意思的吗

**Comment by MR-520DAI** [comment]
UFAST 改为2车道检测非常容易，更改输出和训练数据即可；但是这个算法输出1,2,3,4个车道，他强制设置了一个先验，左车道为2，右车道为3，当车变道时，车道线会位于中间部分，此时车道既不是左，也不是右，因此在变道时中间车道检测非常不准！你可以尝试再增加一维输出1,2,3,4,5，第五个用于输出中间车道。
我之前也是瞎搞搞，主要还是熟悉NCNN框架，这个算法跑通了就没有深入了，也没接触到实际的项目，提供不了太多干货哈

**Comment by MR-520DAI** [comment]
无
